version: '3.7'
services:
  django:
    restart: always
    build: .
    command: gunicorn exercise.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - .:/home/app/web/
    env_file:
      - ./.env
    ports:
      - 8000:8000

  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - django
